# Generated by Django 4.1.2 on 2022-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=300)),
                ('movie_type', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'movietable',
            },
        ),
    ]
