# Generated by Django 4.1.2 on 2022-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('game_rating', models.IntegerField(max_length=5)),
            ],
            options={
                'db_table': 'gametable',
            },
        ),
    ]
