# Generated by Django 4.1.2 on 2022-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_company', models.CharField(max_length=200)),
                ('phone_color', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'phonemodel',
            },
        ),
    ]
