# Generated by Django 4.1.2 on 2022-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_name', models.CharField(max_length=100)),
                ('forest_country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foresttable',
            },
        ),
    ]
